### ISSUE TITLE
Flight Simulator X on Windows 10

### ISSUE THREAD

**Issue by ResidentSage** [TheOtherTimDuncan/TheOtherTimDuncan.github.io#1]
Thank you so much for your blog post on getting FSX to work on Windows 10: http://theothertimduncan.com/archive/Microsoft-Flight-Simulator-Standard-User/

I too didn't want to give my 9 year old administrator accesss, and you saved my bacon!

The fix recently stopped working, and when I looked into it, Microsoft is no longer supporting ACT:
https://www.microsoft.com/en-us/download/details.aspx?id=7352

But they are supporting the same tools inside of their ADK package:
https://developer.microsoft.com/en-us/windows/hardware/windows-assessment-deployment-kit

So I installed the newer ACT tools from there, and the rest of your fix still works great.  Just thought I'd let you know in case you get a chance to update your super helpful post.

Thanks again for guiding us through getting FSX working without admin access!

-Ben

PS. This feels wrong to submit this as an "issue," but your "contact me" link points to here?

**Comment by TheOtherTimDuncan** [comment]
You did the right thing. And technically, the article does have an issue. 😁 When you downloaded the ADK, did you install the entire kit? Do you know which of the individual installers would install the Compatibility Administrator?

**Comment by ResidentSage** [comment]
Hi Tim,

I was able to just install the ACT portion of the ADK.  It's still called ACT in the options you can check off to install.  I unchecked everything else.  Seems to be working well.

Thanks again!

-Ben

**Comment by TheOtherTimDuncan** [comment]
I've updated my article with the info regarding ACT. Thanks for the info.
